version: "2"
services:
  app:
    image: "aymannc/faceid"
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:8.0.1
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro